config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get '/groups', to: 'groups#home'
  get '/groups/new', to: 'groups#new'
  post '/groups/new/submit', to: 'groups#submit'
  get '/group/:id/new_event', to: 'events#new'
  post '/group/:id/new_event', to: 'events#submit', as: 'event_create'
  get '/group/:id', to: 'groups#show', as: 'group_page'
  get '/group/:id/edit', to: 'groups#edit_group', as: 'edit_group'
  patch '/group/:id/edit', to: 'groups#update_group', as: 'update_group'
  get '/group/:id/members', to: 'groups#members', as: 'group_members'
  post '/group/:id', to:'announcements#create'
  get '/group/:id/announcement', to: 'announcements#new', as: 'new_announcement'
  get '/group/:id/announcement/edit/:announcement_id', to:'announcements#edit', as: 'edit_announcement'
  delete '/group/:group_id/announcement/:id', to:'announcements#destroy', as: 'delete_announcement'
  patch '/groups/:id/announcement/:announcement_id', to:'announcements#update', as:'update_announcement'
  get '/group/:id/about', to: 'groups#about', as: 'group_about'
  get '/group/:id/about/edit', to: 'groups#edit_about', as: 'edit_about'
  patch '/groups/:id/about/', to:'groups#update_about', as: 'update_about'
  get '/group/:id/events', to: 'groups#events', as: 'group_events'
  get '/group/:id/media', to: 'groups#media', as: 'group_media'
  get '/group/:id/media/edit', to: 'groups#edit_media', as: 'edit_media'
  patch '/groups/:id/media/', to:'groups#update_media', as: 'update_media'
  post '/groups/change_image', to: 'groups#change_image'

  get '/events', to: 'events#home'
  get '/event/:id', to: 'events#show', as: 'event_page'
  post '/event/add_user', to: 'events#add_user'
  post '/event/remove_user', to: 'events#remove_user'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id/submit', to: 'profiles#submit', as: 'submit_profile'
  get '/signup',  to: 'users#new'
  get '/tos', to: 'static_pages#tos'
  get '/privacy', to: 'static_pages#privacy'

  post '/group/:id/apply', to: 'groups#apply', as: 'apply_to_group'
  post '/group/:id/accept_application/:user_id', to: 'groups#accept', as: 'accept_application'
  post '/group/:id/reject_application/:user_id', to: 'groups#reject', as: 'reject_application'
  post '/group/:id/add_admin/:user_id', to: 'groups#add_admin', as: 'add_admin'
  post '/group/:id/remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :admins
  has_many :group_events
  has_many :applications
  has_many :announcements
  has_many :users, :through => :memberships
  has_many :admin_users, :through => :admins, :source => :user
  has_many :events, :through => :group_events
  has_many :user_apps, :through => :applications, :source => :user

  validates :name, presence: true, length: { maximum: 50 }
  VALID_ZIP_REGEX = /\A\d{5}(-\d{4})?\z|\A\d{3}\z/
  validates :location, presence: true, length: { maximum: 10 }, format: { with: VALID_ZIP_REGEX }
  validates :group_type, presence: true
end

app/controllers/groups_controller.rb
require 'GoogleMapsAPI'
require 'SoundCloudAPI'
require 'YouTubeAPI'
require 'search/DistanceSort'
require 'search/TimeSort'
require 'will_paginate/array'

class GroupsController < ApplicationController
  before_action :set_group_id, only: [:update_about, :update_media, :update_group]
  before_action :set_group_vars, only: [:show, :members, :media, :about, :events, :edit_about, :edit_media, :edit_group]

  def home
    if params[:name].blank?
      @groups = Group.all.to_a
    else
      @groups = Group.where("lower(name) LIKE ?", "%#{params[:name].downcase}%").to_a
    end

    if !(params[:zip].blank?) && @groups.size > 0
      destinations_zips = @groups.map { |g| g.location }
      @destinations = GoogleMapsAPI.get_distances(params[:zip], destinations_zips)
      @strategy = params[:search]
      if params[:search] == "distance"
        strategy = DistanceSort.new
      else
        strategy = TimeSort.new
      end
      @groups = strategy.sort(@groups, @destinations)
    end

    @num_results = @groups.size
    @groups = @groups.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @group_announcements = @group.announcements
    @applied_to_group = (Application.find_by(user: current_user, group_id: params[:id]) != nil) || (@group_members.include?(current_user)) || (@group_admins.include?(current_user))
  end

  def members
    @applied_users = @group.user_apps
  end

  def new
    @group = Group.new
  end

  def submit
    @group = Group.new(group_params)
    @group.users << current_user
    @group.admin_users << current_user

    if (@group.save)
      redirect_to "/group/#{@group.id}"
    else
      render 'new'
    end
  end

  def media
    if !@group.soundcloud_url.blank? && !@group.soundcloud_url.nil?
      @soundcloud_embed_tracks = SoundCloudAPI.get_tracks(@group.soundcloud_url).embed_tracks
    end

    if !@group.youtube_url.blank? && !@group.youtube_url.nil?
      @youtube_embed_tracks = YouTubeAPI.get_videos(@group.youtube_url).embed_videos
    end
  end

  def apply
    application = Application.new
    application.group_id = params[:id]
    application.user = current_user
    if application.save
      redirect_to group_page_path
    end
  end

  def about
    render 'about'
  end

  def reject
    application = Application.find_by(user_id: params[:user_id], group_id: params[:id])
    if application.destroy
      redirect_to group_members_path
    end
  end

  def accept
    # add the user to the group
    group = Group.find_by(id: params[:id])
    group.users << User.find_by(id: params[:user_id])
    
    # delete the application to the group
    application = Application.find_by(user_id: params[:user_id], group_id: params[:id])
    application.destroy

    if group.save
      redirect_to group_members_path
    end
  end

  def events
    @events = @group.events
  end

  def change_image
    group_id = params[:id]
    group = Group.find(group_id)
    group.image_url = params[:image_url]

    if (group.save)
      redirect_to "/group/#{group_id}"
    end
  end

  def add_admin
    @group = Group.find_by(id: params[:id])
    user = User.find_by(id: params[:user_id])
    @group.admin_users << user

    if @group.save
      redirect_to "/group/#{@group.id}/members"
    end
  end

  def remove_member
    @group = Group.find_by(id: params[:id])
    @group_members = @group.users
    @group_admins = @group.admin_users
    @group.memberships.find_by(user_id: params[:user_id]).destroy

    if @group.save
      redirect_to "/group/#{@group.id}/members"
    end
  end

  def update_about
    if @group.update(group_params)
      redirect_to :group_about, notice: 'About page was successfully updated.'
    else
      render :edit_about
    end
  end

  def update_media
    if @group.update(group_params)
      redirect_to :group_media, notice: 'Media page was successfully updated.'
    else
      render :edit_media
    end
  end

  def update_group
    if @group.update(group_params)
      redirect_to :group_page, notice: 'Group page was successfully updated.'
    else
      render :edit_group
    end
  end

  def edit_about
  end

  def edit_media
  end

  def edit_group
  end

  private

  def set_group_vars
    @full_width = true
    @group = Group.find_by(id: params[:id])
    @group_members = @group.users
    @group_admins = @group.admin_users
  end

  def set_group_id
    @group = Group.find_by(id: params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :location, :description, :group_type, :about, :youtube_url, :soundcloud_url)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_header.html.erb
<% provide(:title, @group.name) %>

<div id="group-header">
  <div id="group-header-container" class="container">
    <div id="group-header-right">
      <div id="group-header-photo">
        <%= image_tag @group.image_url.blank? ? "group_default.png" : @group.image_url %>
        <% if current_user && @group_admins.include?(current_user) %>
          <div>Change image</div>
        <% end %>
      </div>
      <div id="group-header-info">
        <div id="group-header-name">
          <%= @group.name %>
        </div>
        <div id="group-header-location">
          <%= @group.location %>
        </div>
        <div id="group-header-description">
          <%= @group.description %>
        </div>
      </div>
    </div>
    <div id="group-header-left">
      <div id="group-header-members">
        <div><i class="material-icons">person_pin</i></div>
        <div>
          <span><%= @group.users.length %></span>
          <% if @group.users.length > 1 %>
            <span>Members</span>
          <% else %>
            <span>Member</span>
          <% end %>
        </div>
      </div>

      <% if current_user && @group_admins.include?(current_user) %>
        <div id="group-header-edit">
          <div class="button">
            <%= link_to edit_group_path, id: "group-header-edit-button" do %>
              <div>Edit Group &nbsp;</div>
              <div><i class="material-icons">create</i></div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if current_user && @group_admins.include?(current_user) %>
  <div id="image-upload-popup" data-id="<%= @group.id %>">
    <input type="file" id="image-upload-file" accept="image/*">
    <label id="image-upload-file-button" for="image-upload-file" class="button">Select an image</label>
    <div id="image-upload-separator">OR</div>
    <input type="text" id="image-upload-text" placeholder="Enter an image url">
    <div id="image-upload-info">Info</div>
    <div id="image-upload-submit" class="button">Submit</div>
  </div>
<% end %>

<div id="group-nav">
  <div class="container">
    <div id="group-nav-bar">
      <% if selected == 'newsfeed' %>
        <div id="group-nav-newsfeed" class="selected">
      <% else %>
        <div id="group-nav-newsfeed">
      <% end %>
        <%= link_to "Newsfeed", :group_page, id: "show-button", class: "group-page-button" %>
      </div>

      <% if selected == 'events' %>
        <div id="group-nav-events" class="selected">
      <% else %>
        <div id="group-nav-events">
      <% end %>
        <%= link_to "Events", :group_events, id: "events-button", class: "group-page-button" %>
      </div>

      <% if selected == 'members' %>
        <div id="group-nav-members" class="selected">
      <% else %>
        <div id="group-nav-members">
      <% end %>
        <%= link_to "Members", :group_members, id: "members-button", class: "group-page-button" %>
      </div>

      <% if selected == 'media' %>
        <div id="group-nav-media" class="selected">
      <% else %>
        <div id="group-nav-media">
      <% end %>
        <%= link_to "Media", :group_media, id: "media-button", class: "group-page-button" %>
      </div>

      <% if selected == 'about' %>
        <div id="group-nav-about" class="selected">
      <% else %>
        <div id="group-nav-about">
      <% end %>
        <%= link_to "About", :group_about, id: "about-button", class: "group-page-button" %>
      </div>
    </div>
  </div>
</div>

app/views/groups/about.html.erb
<%= render partial: 'header', locals: {selected: 'about'} %>

<div class="container">
  <% if current_user && @group_admins.include?(current_user) %>
    <div id="edit-about">
      <div class="button">
        <%= link_to edit_about_path, id: "edit-about-button" do %>
          <div>Edit About &nbsp;</div>
          <div><i class="material-icons">create</i></div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if !@group.about.nil? && !@group.about.blank? %>
    <div id="group-body">
      <%= simple_format(@group.about.html_safe) %>
    </div>
  <% end %>
</div>

app/views/groups/edit_about.html.erb
<%= render partial: 'header', locals: {selected: 'about'} %>

<div class="container">
  <h1>Editing About</h1>

  <div class="back-button">
    <div class="button">
      <%= link_to :group_about do %>
        <div><i class="material-icons">arrow_back</i></div>
        <div>&nbsp; Back</div>
      <% end %>
    </div>
  </div>

  <%= form_for @group, :url => { :controller => :groups, :action => :update_about} do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="edit-group-form">
      <div>
        <%= f.label :about %>
        <%= f.text_area :about, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "Edit About", class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit_group.html.erb
<%= render partial: 'header', locals: {selected: 'newsfeed'} %>

<div class="container">
  <h1>Editing Group</h1>

  <div class="back-button">
    <div class="button">
      <%= link_to :group_page do %>
        <div><i class="material-icons">arrow_back</i></div>
        <div>&nbsp; Back</div>
      <% end %>
    </div>
  </div>

  <%= form_for @group, :url => { :controller => :groups, :action => :update_group} do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="edit-group-form">
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :location, "Zip code" %>
        <%= f.text_field :location, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :group_type %>
        <%= f.text_field :group_type, class: 'form-control' %>
      </div>
      <div>
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="actions">
        <%= f.submit "Edit Group", class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit_media.html.erb
<%= render partial: 'header', locals: {selected: 'media'} %>

<div class="container">
  <h1>Editing Media</h1>

  <div class="back-button">
    <div class="button">
      <%= link_to :group_media do %>
        <div><i class="material-icons">arrow_back</i></div>
        <div>&nbsp; Back</div>
      <% end %>
    </div>
  </div>

  <%= form_for @group, :url => { :controller => :groups, :action => :update_media} do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
        <% @group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="edit-group-form">
      <div>
      <%= f.label :youtube_url, "URL to YouTube page" %>
      <%= f.text_field :youtube_url, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :soundcloud_url, "SoundCloud Username" %>
      <%= f.text_field :soundcloud_url, class: 'form-control' %>
    </div>
      <div class="actions">
        <%= f.submit "Edit Media", class: "button" %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/events.html.erb
<%= render partial: 'header', locals: {selected: 'events'} %>

<div class="container">
  <h1>Scheduled Events</h1>
  
  <% if current_user && @group_admins.include?(current_user) %>
    <div id="group-events-new-button">
      <div class="button">
        <%= link_to "/group/#{@group.id}/new_event", id: "new-event-button" do %>
          <div>New Event &nbsp;</div>
          <div><i class="material-icons">event</i></div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div id="group-events-results">
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Description</th>
          <th>Location</th>
          <th>Date</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @events.length == 0 %>
          <tr>
            <td colspan="6" style="text-align: center; font-size: 20px; padding: 40px 0;"><i>No Events Scheduled</i></td>
          </tr>
        <% else %>
          <% @events.each do |event| %>
            <tr>
              <td><%= image_tag(event.image, class: "event-thumbnail") unless event.image.blank? %></td>
              <td><%= event.name %></td>
              <td><%= event.description %></td>
              <td><%= event.location %></td>
              <td><%= event.start_datetime.strftime("%B %-d, %Y") unless event.start_datetime.nil? %></td>
              <td><a href="/event/<%= event.id %>"><i class="material-icons">open_in_browser</i></a></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/home.html.erb
<% provide(:title, "Groups") %>
<h1>Groups</h1>

<div id="find-groups-top">
  <div id="find-groups-header">
    <div id="find-groups-title">Find Groups</div>
    <% if current_user %>
      <div class="button">
        <%= link_to "New Group", "/groups/new", id: "new-group-button" %>
      </div>
    <% end %>
  </div>

  <div id="find-groups-search-container">
  <%= form_tag groups_path, :id => 'find-groups-searches', :method => 'get' do %>
    <div id="find-groups-by-name">
      <label>Name</label>
        <%= text_field_tag :name, params[:name], :id => 'search-name-input', placeholder: "Enter Name" %>
    </div>
    <div id="find-groups-by-zip">
      <label>Zip Code</label>
        <%= text_field_tag :zip, params[:zip], :id => 'search-zip-input', placeholder: "Enter Zip" %>
    </div>
    <div id="zip-search-strategy" style="display: none">
      <div>
        <%= radio_button_tag(:search, "distance") %>
        <%= label_tag(:search_dist, "Search by distance") %>
      </div>
      <div>
        <%= radio_button_tag(:search, "time") %>
        <%= label_tag(:search_time, "Search by time") %>
      </div>
    </div>
    <%= submit_tag "Search", :id => 'search-groups-button', :class => 'button' %>
  <% end %>
  </div>
</div>

<div id="find-groups-results-container">
  <div id="find-groups-results-header">
    <div id="find-groups-results-title">Results</div>
    <div id="find-groups-results-count"><%= @num_results %> Found</div>
  </div>
  <%= will_paginate %>
  <div id="find-groups-results">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Type</th>
          <th>Location</th>
          <% if defined?(@destinations) %>
            <% if @strategy == "distance" %>
              <th>Distance</th>
            <% elsif @strategy == "time" %>
              <th>Duration</th>
            <% end %>
          <% end %>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td><%= group.description %></td>
            <td><%= group.group_type %></td>
            <td><%= group.location %></td>
            <% if defined?(@destinations) %>
              <% if @strategy == "distance" %>
                <td><%= @destinations.distances[group.location][:text] %> away</td>
              <% elsif @strategy == "time" %>
                <td><%= @destinations.durations[group.location][:text] %> away</td>
              <% end %>
            <% end %>
            <td><a href="/group/<%= group.id %>"><i class="material-icons">open_in_browser</i></a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate %>
</div>

<script type="text/javascript">
$("#search-zip-input").keyup(function() {
  if($(this).val()) {
      $("#zip-search-strategy").show();
  } else {
      $("#zip-search-strategy").hide();
  }
})
</script>

app/views/groups/media.html.erb
<%= render partial: 'header', locals: {selected: 'media'} %>

<div class="container">
  <% if current_user && @group_admins.include?(current_user) %>
    <div id="edit-media">
      <div class="button">
        <%= link_to edit_media_path, id: "edit-media-button" do %>
          <div>Edit Media &nbsp;</div>
          <div><i class="material-icons">create</i></div>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if defined? @soundcloud_embed_tracks %>
  <h1>SoundCloud Tracks</h1>

  <div id="soundcloud-tracks-list">
    <% @soundcloud_embed_tracks.each do |track| %>
      <div class="soundcloud-track">
        <div class="soundcloud-track-date">
          <i>(<%= time_ago_in_words(track[:date]) %> ago)</i>
        </div>
        <div class="soundcloud-track-body"><%= track[:embed_html].html_safe %></div>
      </div>
    <% end %>
  </div>
  <% end %>

  <% if defined? @youtube_embed_tracks %>
  <h1>YouTube Tracks</h1>

  <div id="youtube-tracks-list">
    <% @youtube_embed_tracks.each do |track| %>
      <div class="youtube-track">
        <div class="youtube-track-date">
          <i>(<%= time_ago_in_words(track[:date]) %> ago)</i>
        </div>
        <div class="youtube-track-body"><%= track[:embed_html].sub('width="480"', 'width="100%"').html_safe %></div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/groups/members.html.erb
<%= render partial: 'header', locals: {selected: 'members'} %>

<div class="container">

  <% if current_user && @group_admins.include?(current_user) %>
    <h1>Pending Applications</h1>
    
    <div id="pending-applications-list">
      <% @applied_users.each do |user| %>
      <div class="pending-application-item">
        <div class="pending-application-profile">
          <div class="pending-application-picture">
            <%= image_tag "https://graph.facebook.com/#{user.uid}/picture?type=square" %>
          </div>
          <div class="pending-application-name">
            <%= user.name %>
          </div>
        </div>

        <div class="pending-application-options">
          <div>
            <%= link_to accept_application_path(:id => @group.id, :user_id => user.id), method: :post do %>
              <i class="material-icons">check</i>
            <% end %>
          </div>
          <div>
            <%= link_to reject_application_path(:id => @group.id, :user_id => user.id), method: :post do %>
              <i class="material-icons">clear</i>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>

  <div id="group-members">
    <h1>Admins</h1>

    <div class="group-admins-list">
      <% @group_admins.each do |admin| %>
        <div class="group-admin-item">
          <div class="group-admin-profile">
            <div class="group-admin-picture">
              <%= image_tag "https://graph.facebook.com/#{admin.uid}/picture?type=square" %>
            </div>
            <div class="group-admin-name">
              <%= admin.name %>
            </div>
          </div>

          <div class="group-admin-options">
            <div>
              <a href="/profile/<%= admin.uid %>"><i class="material-icons">open_in_browser</i></a>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <h1>Members</h1>

    <div class="group-members-list">
      <% @group_members.each do |member| %>
        <% if !@group_admins.include?(member) %>
          <div class="group-member-item">
            <div class="group-member-profile">
              <div class="group-member-picture">
                <%= image_tag "https://graph.facebook.com/#{member.uid}/picture?type=square" %>
              </div>
              <div class="group-member-name">
                <%= member.name %>
              </div>
            </div>

            <div class="group-member-options">
              <% if current_user && @group_admins.include?(current_user) %>
                <div>
                  <%= link_to remove_member_path(:id => @group.id, :user_id => member.id), method: :post do %>
                  <i class="material-icons">clear</i>
                  <% end %>
                </div>
                <div>
                  <%= link_to add_admin_path(:id => @group.id, :user_id => member.id), method: :post do %>
                  <i class="material-icons">person_add</i>
                  <% end %>
                </div>
              <% end %>
              <div>
                <a href="/profile/<%= member.uid %>"><i class="material-icons">open_in_browser</i></a>
              </div>
            </div>
          </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% provide(:title, "New Group") %>

<h1>Create New Group</h1>

<%= form_for @group, :url => { :controller => :groups, :action => :submit} do |f| %>
  <div id="new-group-form">
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :location, "Zip code" %>
      <%= f.text_field :location, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :group_type %>
      <%= f.text_field :group_type, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :about %>
      <%= f.text_area :about, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :youtube_url, "URL to YouTube page" %>
      <%= f.text_field :youtube_url, class: 'form-control' %>
    </div>
    <div>
      <%= f.label :soundcloud_url, "SoundCloud Username" %>
      <%= f.text_field :soundcloud_url, class: 'form-control' %>
    </div>
    <div>
      <%= f.submit "Create Group", class: "button" %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<%= render partial: 'header', locals: {selected: 'newsfeed'} %>

<div id="group-body">
  <div class="container">
    <div class="group-newsfeed">
      <% if !@applied_to_group %>
        <div id="group-newsfeed-apply-button">
          <div class="button">
            <%= link_to "/group/#{@group.id}/apply", id: "apply-to-group-button",  method: :post, remote: true do %>
              <div>Apply to Group &nbsp;</div>
              <div><i class="material-icons">assignment_ind</i></div>
            <% end %>
          </div>
        </div>
      <% end %>
      
      <% if current_user && @group_admins.include?(current_user) %>
        <div id="group-newsfeed-new-button">
          <div class="button">
            <%= link_to :new_announcement, id: "new-announcement-button" do %>
              <div>New Post &nbsp;</div>
              <div><i class="material-icons">create</i></div>
            <% end %>
          </div>
        </div>
      <% end %>

      <% @group_announcements.each do |announcement| %>
        <div class="group-newsfeed-item">
          <div class="group-newsfeed-item-top">
            <div>
              <span class="group-newsfeed-item-title"><%= announcement.title %></span>
              <span class="group-newsfeed-item-date">
                <i>(<%= time_ago_in_words(announcement.created_at) %> ago)</i>
              </span>
            </div>
            <div class="group-newsfeed-item-controls">
              <% if current_user && @group_admins.include?(current_user) %>
                <%= link_to edit_announcement_path(:announcement_id => announcement.id) do %>
                  <i class="material-icons">edit</i>
                <% end %>
                <%= link_to delete_announcement_path(announcement, :group_id => @group.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="material-icons">clear</i>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="group-newsfeed-item-body"><%= simple_format(announcement.description) %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>