config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get '/groups', to: 'groups#home'
  get '/groups/new', to: 'groups#new'
  post '/groups/new/submit', to: 'groups#submit'
  get '/group/:id/new_event', to: 'events#new'
  post '/group/:id/new_event', to: 'events#submit', as: 'event_create'
  get '/group/:id', to: 'groups#show', as: 'group_page'
  get '/group/:id/edit', to: 'groups#edit_group', as: 'edit_group'
  patch '/group/:id/edit', to: 'groups#update_group', as: 'update_group'
  get '/group/:id/members', to: 'groups#members', as: 'group_members'
  post '/group/:id', to:'announcements#create'
  get '/group/:id/announcement', to: 'announcements#new', as: 'new_announcement'
  get '/group/:id/announcement/edit/:announcement_id', to:'announcements#edit', as: 'edit_announcement'
  delete '/group/:group_id/announcement/:id', to:'announcements#destroy', as: 'delete_announcement'
  patch '/groups/:id/announcement/:announcement_id', to:'announcements#update', as:'update_announcement'
  get '/group/:id/about', to: 'groups#about', as: 'group_about'
  get '/group/:id/about/edit', to: 'groups#edit_about', as: 'edit_about'
  patch '/groups/:id/about/', to:'groups#update_about', as: 'update_about'
  get '/group/:id/events', to: 'groups#events', as: 'group_events'
  get '/group/:id/media', to: 'groups#media', as: 'group_media'
  get '/group/:id/media/edit', to: 'groups#edit_media', as: 'edit_media'
  patch '/groups/:id/media/', to:'groups#update_media', as: 'update_media'
  post '/groups/change_image', to: 'groups#change_image'

  get '/events', to: 'events#home'
  get '/event/:id', to: 'events#show', as: 'event_page'
  post '/event/add_user', to: 'events#add_user'
  post '/event/remove_user', to: 'events#remove_user'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id/submit', to: 'profiles#submit', as: 'submit_profile'
  get '/signup',  to: 'users#new'
  get '/tos', to: 'static_pages#tos'
  get '/privacy', to: 'static_pages#privacy'

  post '/group/:id/apply', to: 'groups#apply', as: 'apply_to_group'
  post '/group/:id/accept_application/:user_id', to: 'groups#accept', as: 'accept_application'
  post '/group/:id/reject_application/:user_id', to: 'groups#reject', as: 'reject_application'
  post '/group/:id/add_admin/:user_id', to: 'groups#add_admin', as: 'add_admin'
  post '/group/:id/remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    if current_user
      @groups = current_user.groups

      events = []
      announcements = []

      @groups.each do |group|
        events.concat(group.events)
        announcements.concat(group.announcements)
      end

      @news = []

      events.each do |event|
        @news.push({
          type: 'event',
          post: event
        })
      end

      announcements.each do |announcement|
        @news.push({
          type: 'announcement',
          post: announcement
        })
      end

      @news = @news.sort_by { |news_post| news_post[:post].created_at }.reverse
    else
      render 'static_pages/home' unless current_user
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<h1>Your Groups</h1>

<div id="home-groups">
  <% @groups.each do |group| %>
    <div class="home-groups-item">
      <div class="home-groups-item-top">
        <div>
          <span class="home-groups-item-title">
            <%= group.name %>
          </span>
        </div>
        <div>
          <%= link_to group_page_path(id: group.id) do %>
            <i class="material-icons">open_in_browser</i>
          <% end %>
        </div>
      </div>
      <div class="home-groups-item-body">
        <%= group.description %>
      </div>
    </div>
  <% end %>
</div>

<h1>Your Newsfeed</h1>

<div id="home-newsfeed">
  <% @news.each do |news_post| %>
    <div class="home-newsfeed-item">
      <% if news_post[:type] == 'event' %>

        <div class="home-newsfeed-item-top">
          <div>
            <span class="home-newsfeed-item-title"><%= news_post[:post].name %>
            </span>
            <span>
              <i>hosted by <b><%= news_post[:post].groups.first.name %></b></i>
            </span>
          </div>
          <div class="home-newsfeed-item-date">
            <i><%= time_ago_in_words(news_post[:post].created_at) %> ago</i>
          </div>
        </div>
        <div class="group-newsfeed-item-body"><%= news_post[:post].description %></div>

      <% elsif news_post[:type] == 'announcement' %>

       <div class="home-newsfeed-item-top">
          <div>
            <span class="home-newsfeed-item-title"><%= news_post[:post].title %></span>
            <span>
              <i>in <b><%= news_post[:post].group.name %></b></i>
            </span>
          </div>
          <div class="home-newsfeed-item-date">
            <i><%= time_ago_in_words(news_post[:post].created_at) %> ago</i>
          </div>
        </div>
        <div class="group-newsfeed-item-body"><%= news_post[:post].description %></div>

      <% end %>
    </div>
  <% end %>
</div>