config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  get '/groups', to: 'groups#home'
  get '/groups/new', to: 'groups#new'
  post '/groups/new/submit', to: 'groups#submit'
  get '/group/:id/new_event', to: 'events#new'
  post '/group/:id/new_event', to: 'events#submit', as: 'event_create'
  get '/group/:id', to: 'groups#show', as: 'group_page'
  get '/group/:id/edit', to: 'groups#edit_group', as: 'edit_group'
  patch '/group/:id/edit', to: 'groups#update_group', as: 'update_group'
  get '/group/:id/members', to: 'groups#members', as: 'group_members'
  post '/group/:id', to:'announcements#create'
  get '/group/:id/announcement', to: 'announcements#new', as: 'new_announcement'
  get '/group/:id/announcement/edit/:announcement_id', to:'announcements#edit', as: 'edit_announcement'
  delete '/group/:group_id/announcement/:id', to:'announcements#destroy', as: 'delete_announcement'
  patch '/groups/:id/announcement/:announcement_id', to:'announcements#update', as:'update_announcement'
  get '/group/:id/about', to: 'groups#about', as: 'group_about'
  get '/group/:id/about/edit', to: 'groups#edit_about', as: 'edit_about'
  patch '/groups/:id/about/', to:'groups#update_about', as: 'update_about'
  get '/group/:id/events', to: 'groups#events', as: 'group_events'
  get '/group/:id/media', to: 'groups#media', as: 'group_media'
  get '/group/:id/media/edit', to: 'groups#edit_media', as: 'edit_media'
  patch '/groups/:id/media/', to:'groups#update_media', as: 'update_media'
  post '/groups/change_image', to: 'groups#change_image'

  get '/events', to: 'events#home'
  get '/event/:id', to: 'events#show', as: 'event_page'
  post '/event/add_user', to: 'events#add_user'
  post '/event/remove_user', to: 'events#remove_user'

  get '/profile/:id', to: 'profiles#show', as: 'profile'
  get '/profile/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profile/:id/submit', to: 'profiles#submit', as: 'submit_profile'
  get '/signup',  to: 'users#new'
  get '/tos', to: 'static_pages#tos'
  get '/privacy', to: 'static_pages#privacy'

  post '/group/:id/apply', to: 'groups#apply', as: 'apply_to_group'
  post '/group/:id/accept_application/:user_id', to: 'groups#accept', as: 'accept_application'
  post '/group/:id/reject_application/:user_id', to: 'groups#reject', as: 'reject_application'
  post '/group/:id/add_admin/:user_id', to: 'groups#add_admin', as: 'add_admin'
  post '/group/:id/remove_member/:user_id', to: 'groups#remove_member', as: 'remove_member'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/announcement.rb
class Announcement < ApplicationRecord
	belongs_to :group

	validates :title, presence: true, length: { maximum: 50 }
	validates :description, presence: true
end

app/models/application.rb
class Application < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :group_events
  has_many :event_users
  has_many :groups, :through => :group_events
  has_many :users, :through => :event_users

  validates :name, presence: true, length: { maximum: 50 }
  VALID_ZIP_REGEX = /\A\d{5}(-\d{4})?\z|\A\d{3}\z/
  validates :location, presence: true, length: { maximum: 10 }, format: { with: VALID_ZIP_REGEX }
  validates :start_datetime, presence: true
  validates :image, format: { with: URI::regexp(%w(http https))}, :allow_blank => true
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :admins
  has_many :group_events
  has_many :applications
  has_many :announcements
  has_many :users, :through => :memberships
  has_many :admin_users, :through => :admins, :source => :user
  has_many :events, :through => :group_events
  has_many :user_apps, :through => :applications, :source => :user

  validates :name, presence: true, length: { maximum: 50 }
  VALID_ZIP_REGEX = /\A\d{5}(-\d{4})?\z|\A\d{3}\z/
  validates :location, presence: true, length: { maximum: 10 }, format: { with: VALID_ZIP_REGEX }
  validates :group_type, presence: true
end

app/models/group_event.rb
class GroupEvent < ApplicationRecord
	belongs_to :group
	belongs_to :event
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	serialize :availability, Array

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, allow_blank: true, length: { maximum: 200 }, format: { with: VALID_EMAIL_REGEX }
  validates :musical_role, length: { maximum: 50 }
  validates :interests, length: { maximum: 100 }
  validates :other, length: { maximum: 100 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :admins
  has_many :applications
  has_many :event_users
  has_many :groups, :through => :memberships
  has_many :admined_groups, :through => :admins, :source => :groups
  has_many :group_apps, :through => :applications
  has_many :events, :through => :event_users

  has_one :profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.save
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    if current_user
      @groups = current_user.groups

      events = []
      announcements = []

      @groups.each do |group|
        events.concat(group.events)
        announcements.concat(group.announcements)
      end

      @news = []

      events.each do |event|
        @news.push({
          type: 'event',
          post: event
        })
      end

      announcements.each do |announcement|
        @news.push({
          type: 'announcement',
          post: announcement
        })
      end

      @news = @news.sort_by { |news_post| news_post[:post].created_at }.reverse
    else
      render 'static_pages/home' unless current_user
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "MusicSpot"
    if page_title.empty?
      base_title
    else
      base_title + " | " + page_title
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div id="logo">
      <%= link_to "MusicSpot", root_path %>
    </div>
    <nav id="desktop-nav">
      <ul id="navbar">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Groups", groups_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <% if current_user %>
          <li><%= link_to "Profile", profile_path(:id => current_user.uid), id: "profile" %></li>
          <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
        <% else %>
          <li><%= link_to "Log in", "/auth/facebook", id: "sign_in" %></li>
        <% end %>
      </ul>
    </nav>
    <nav id="mobile-nav">
      <div><i id="mobile-nav-menu" class="material-icons">menu</i></div>
    </nav>
  </div>
</header>

<ul id="mobile-navbar">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Groups", groups_path %></li>
  <li><%= link_to "Events", events_path %></li>
  <% if current_user %>
    <li><%= link_to "Profile", profile_path(:id => current_user.uid), id: "profile" %></li>
    <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
  <% else %>
    <li><%= link_to "Log in", "/auth/facebook", id: "sign_in" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag 'logo_bold.png' %>

    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Quicksand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="blanket"></div>

    <% if !@full_width %>
      <div class="container">
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>